<?php

namespace Database\Seeders;

use App\Models\BonusJobTitle;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class BonusJobTitleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {




        BonusJobTitle::create(['name' => 'مهندس اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مبرمجين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'مدير مخازن اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس ممرض اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مضيفين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'منقب اثار اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس نطم معلومات اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس كيمياوين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس فيزياوين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس بايولوجين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس احصائيين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مترجمين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'مدير اعلامي اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مهندسيين زراعيين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مشرفيين سياحيين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس ابحاث اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس جيولوجين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'مستشار قانوني', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس صحة بيئة اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'مستشار سياسي اقدم', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'طبيب بيطري استشاري', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس منتج اغذية اقدم', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'خبير جودة', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'محقق عدل اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مصممين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مصححين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس مهندسين تقنين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'مرشد تربوي اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس امناء مكتبة اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'رئيس متنبئين جويين اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'معلم جامعي اقدم اول', 'bonus_degree_id' => 1]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي اقدم اول', 'bonus_degree_id' => 1]);



        BonusJobTitle::create(['name' => 'مدير تدقيق حسابات اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير حسابات اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير فني اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير تدقيق اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مهندسين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدرس اقدم ثاني', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مبرمجين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير مخازن اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'معلم اقدم ثاني', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس ممرض جامعي أقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مرشدين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مشرف بيانات اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مضيفين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مراقبين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مراقبين جويين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'واعظ اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'منقب اثار اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس اختصاصي نظم ومعلومات أقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس كيمياويين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس فيزياويين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس بايولوجين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس احصائيين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مترجمين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مدير اعلامي اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مهندسيين زراعين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مشرفيين سياحيين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس ابحاث اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس جيولوجي اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مستشار قانوني مساعد', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس صحة بيئة', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مستشار سياسي', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس اطباء بييطرين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس منتج اغذية', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس اختصاص جودة اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس فاحصي مواد', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مدربين رياضين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'محقق عدل اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مصممين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مصححين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس مهندسيين تقنيين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس محللين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مرشد تربوي اقدم ثاني', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس امين مكتبة اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'رئيس متنبئين جويين اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'معلم جامعي اقدم ثاني', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي اقدم', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'مشرف فني اقدم ثاني', 'bonus_degree_id' => 2]);
        BonusJobTitle::create(['name' => 'محقق قضائي اقدم', 'bonus_degree_id' => 2]);

        BonusJobTitle::create(['name' => 'مدير تدقيق حسابات', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير حسابات', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير فني', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير تدقيق', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مهندسين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدرس اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مبرمجين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير مخازن', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس رسامين هندسيين اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مساحين اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'معلم اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس ممرضين وممرضة جامعية', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مرشدين زراعيين اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مرشدين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مشرف بيانات اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مرشدين اجتماعين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مضيفين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مراقبيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مراقبين جويين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس رسامين اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'امام اول', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس راصد جوي', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'واعظ اول', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'منقب اثار اول', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس اختصاصي نظم ومعلومات', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس كيمياويين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس فيزياويين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس بايولوجي', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس احصائيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مترجمين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مدير اعلامي', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مهندسين زراعيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مشرفيين سياحيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس ابحاث', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس جيولوجي', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مشاور قانوني اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'معاون رئيس صحة بيئة', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مشاور سياسي اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس اطباء بييطرين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'معاون رئيس منتج اغذية', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس اختصاص جودة', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'معاون رئيس فاحصي مواد', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مدربين رياضيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'محقق عدلي اول', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مصممين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مصححين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس مهندسين تقنيين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس محللي انظمة', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مرشد تربوي اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس امين مكتبة', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'رئيس متنبئين جويين', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'معلم جامعي اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي اول', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'مشرف فني اقدم', 'bonus_degree_id' => 3]);
        BonusJobTitle::create(['name' => 'محقق قضائي اول', 'bonus_degree_id' => 3]);

        BonusJobTitle::create(['name' => 'رئيس كتاب طابعة اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير تدقيق حسابات', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير حسابات', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير فني', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير تدقيق', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مهندسين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'مدرس اول', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مبرمجين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير مخازن', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس رسامين هندسي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس مساحين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معلم اول', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس ممرض أو رئيسة ممرضات اقدم – رئيس معاون طبي اقدم – معاون رئيس ممرض وممرضة جامعية – رئيس او رئيسة ممرض او ممرضة ماهرة اقدم-رئيس مضمدين اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس مرشدين زراعيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مرشدين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس مشرف بيانات', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مضيفين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'محرر اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مراقبيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مراقبين جويين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'رئيس رسامين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'امام ثاني', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس راصد جوي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'واعظ ثان', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'منقب اثار ثان', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس اختصاصي نظم ومعلومات', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس كيمياويين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس فيزيائيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس بايولوجي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس احصائيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مترجمين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون مدير اعلامي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مهندسين زراعين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مشرفيين سياحيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس ابحاث', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس جيولوجي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'مشاور قانوني', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'باحث صحة بيئة اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'مشاور سياسي', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'طبيب بيطري ممارس اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'منتج اغذية اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'م.ر. اختصاص جودة', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'فاحص مواد اقدم', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مدربين رياضيين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'محقق عدلي ثان', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مصممين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مصححين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس مهندسين تقني', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس محللي انظمة', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'مرشد تربوي اول', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس امين مكتبة', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معاون رئيس متنبئين جويين', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'معلم جامعي اول', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي ثان', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'مشرف فني اول', 'bonus_degree_id' => 4]);
        BonusJobTitle::create(['name' => 'محقق قضائي ثان', 'bonus_degree_id' => 4]);


        BonusJobTitle::create(['name' => 'ر.حرفيين اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس سواق اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس حراس اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مؤذن اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس امين صندوق', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس كتاب طابعة', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مدقق حسابات اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'محاسب اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس ملاحظين', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس ملاحظين فني', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مدقق اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مهندس اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مدرس ثاني', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مبرمج اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'امين مخزن اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'م.ر. رسامين هندسي', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'معاون رئيس مساحين', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'معلم ثاني', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس معاون طبي – ممرض او ممرضة جامعية اقدم – رئيس ممرض او ممرضة ماهرة – رئيس ممرض او ممرضة', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'معاون رئيس مرشدين زراعيين', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مرشد اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'معاون رئيس مشرف بيانات', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مرشد اجتماعي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مضيف اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'محرر اول', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مراقب اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مراقب جوي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'م.ر. رسامين', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'امام ثالث', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'راصد جوي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'واعظ ثالث', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'منقب اثار ثالث', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'اختصاصي نظم ومعلومات اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'كيمياوي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'فيزياوي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'بايولوجي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'احصائي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مترجم اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'رئيس ملاحظين اعلامي', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مهندس زراعي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مشرف سياحي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'باحث اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'جيولوجي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مشاور قانوني مساعد', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'باحث صحة بيئة اول', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مساعد مشاور سياسي', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'طبيب بيطري ممارس', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'منتج اغذية اول', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'اختصاص جودة اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'فاحص مواد اول', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مدرب رياضي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'محقق عدلي ثالث', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مصمم اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مصحح اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مهندس تقني اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'محلل انظمة اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مرشد تربوي ثاني', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'امين مكتبة اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'متنبئ جوي اقدم', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'معلم جامعي ثاني', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي ثالث', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'مشرف فني ثان', 'bonus_degree_id' => 5]);
        BonusJobTitle::create(['name' => 'محقق قضائي ثالث', 'bonus_degree_id' => 5]);

        BonusJobTitle::create(['name' => 'رئيس حرفيين', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'رئيس سواق', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'رئيس حراس', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مؤذن اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'معاون رئيس امين صندوق', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'معاون رئيس كتاب طابعة', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مدقق حسابات', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'محاسب', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'ملاحظ', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'ملاحظ فني', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مدقق', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مهندس', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مدرس ثالث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مبرمج', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'امين مخزن', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'رسام هندسي اقدم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مساح اقدم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'معلم ثالث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'معاون رئيس معاون طبي – ممرض وممرضة جامعية – معاون رئيس ممرض وممرضة ماهرة – معاون رئيس او رئيسة ممرضات-معاون رئيس مضمدين', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مرشد زراعي اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مرشد اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مشرف بيانات اقدم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مرشد اجتماعي اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مضيف', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'محرر ثان', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مراقب اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مراقب جوي اول', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'رسام اقدم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'امام رابع', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'راصد جوي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'واعظ رابع', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'منقب اثار رابع', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'اختصاصي نظم ومعلومات', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'كيمياوي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'فيزياوي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'بايولوجي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'إحصائي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مترجم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'ملاحظ اعلامي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مهندس زراعي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مشرف سياحي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'باحث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'جيولوجي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'قانوني', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'باحث صحي بيئة', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'باحث سياسي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'منتج اغذية', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'اختصاص جودة', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'فاحص مواد', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مدرب رياضي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'محقق عدلي رابع', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مصمم', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مصحح', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مهندس تقني', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'محلل انطمة', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مرشد تربوي ثالث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'امين مكتبة', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'متنبئ جوي', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'معلم جامعي ثالث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي رابع', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'مشرف فني ثالث', 'bonus_degree_id' => 6]);
        BonusJobTitle::create(['name' => 'محقق قضائي رابع', 'bonus_degree_id' => 6]);



        BonusJobTitle::create(['name' => 'معاون رئيس حرفيين', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون رئيس سواق', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون رئيس حراس', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مؤذن ثان', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'امين صندوق اقدم', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'كاتب طابعة اقدم', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'م مدقق حسابات', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون محاسب', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون ملاحظ', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون ملاحظ فني', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مدقق', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مهندس', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مدرس رابع', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مبرمج', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'م.امين مخزن', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'رسام هندسي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مساح', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معلم رابع', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'م.طبي اقدم – ممرض وممرضة جامعية متدرب – ممرض او ممرضة اقدم- ممرض فني اقدم', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مرشد زراعي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مرشد', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مشرف بيانات', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مرشد اجتماعي ثان', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مضيف اول', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'محرر ثالث', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مراقب', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مراقب جوي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'رسام', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'امام', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون راصد جوي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'واعظ خامس', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'منقب اثار', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون اختصاص نظم ومعلومات', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون كيمياوي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون فيزياوي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون بايولوجي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون إحصائي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مترجم', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون ملاحظ اعلامي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مهندس زراعي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مشرف سياحي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون باحث', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون جيولوجي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون قانوني', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون باحث صحي بيئة', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مساعد باحث سياسي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون منتج اغذية', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون اختصاص جودة', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون فاحص مواد', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مدرب رياضي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'محقق عدلي خامس', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'م.مصمم', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'م مصحح', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون مهندس تقني', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون محلل انظمة', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مرشد تربوي رابع', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون امين مكتبة', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معاون متنبئ جوي', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'معلم جامعي رابع', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'باحث اجتماعي خامس', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'مشرف فني رابع', 'bonus_degree_id' => 7]);
        BonusJobTitle::create(['name' => 'محقق قضائي خامس', 'bonus_degree_id' => 7]);



        BonusJobTitle::create(['name' => 'حارس اقدم', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'مؤذن ثالث', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'امين صندوق', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'كاتب طابعة اول', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'كاتب حسابات', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'كاتب', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'فني', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'كاتب تدقيق', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'كاتب مخزن', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون رسام هندسي', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مساح', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معلم خامس', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'م.طبي – ممرضة فنية – ممرض او ممرضة ماهرة – ممرض او ممرضة م طبي متدرب -م مختبر طبي-مضمد-م طبي تدرج', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'مراقب زراعي', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مرشد', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مشرف بيانات /مسجل بيانات /مراجع بيانات', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مرشد اجتماعي', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'مضيف ثاني', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون محرر', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مراقب', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون مراقب جوي', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون رسام', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون امام', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'راصد جوي متدرب', 'bonus_degree_id' => 8]);
        BonusJobTitle::create(['name' => 'معاون واعظ', 'bonus_degree_id' => 8]);

        BonusJobTitle::create(['name' => 'موظف خدمات اقدم', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'موظف خدمات اقدم', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'حرفي اول', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'سائق اول', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'حارس اول', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'مؤذن رابع', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'معاون امين صندوق', 'bonus_degree_id' => 9]);
        BonusJobTitle::create(['name' => 'كاتب طابعة ثاني', 'bonus_degree_id' => 9]);


        BonusJobTitle::create(['name' => 'موظف خدمات /م موظف خدمات', 'bonus_degree_id' => 10]);
        BonusJobTitle::create(['name' => 'م حرفي/حرفي', 'bonus_degree_id' => 10]);
        BonusJobTitle::create(['name' => 'سائق ثالث /سائق ثاني', 'bonus_degree_id' => 10]);
        BonusJobTitle::create(['name' => 'حارس ثالث/حارس ثاني', 'bonus_degree_id' => 10]);
        BonusJobTitle::create(['name' => 'مؤذن سادس/مؤذن خامس', 'bonus_degree_id' => 10]);
        BonusJobTitle::create(['name' => 'كاتب طابعة ثالث', 'bonus_degree_id' => 10]);


        // BonusJobTitle::create(['name' => '', 'bonus_degree_id' => 10]);

    }
}
